Initial OSSF repository docs
ossf/Memory-Safety pull request #1
Opened 2023-04-10 04:48 UTC by balteravishay

This PR proposes an initial readme and charter docs, as well as linting GH actions and settings yaml file for the memory safety SIG, forming under the OSSF BEST WG.

2023-04-10 05:01 UTC, ljharb requested changes

2023-04-10 05:27 UTC, balteravishay commented on .github/settings.yml
>      permission: push
thanks for the review!
the intention was not to provide access rights to myself where i aught not have them, but to follow how other repositories in the OSSF org have implemented the settings file, for instance the [vulnerability disclosures WG](https://github.com/ossf/wg-vulnerability-disclosures/blob/main/.github/settings.yml), the [supply chain integrity WG](https://github.com/ossf/wg-supply-chain-integrity/blob/main/.github/settings.yml).
Should I leave the collaborators part empty, as the template was, if that is the intention?

2023-04-10 07:26 UTC, ljharb commented on .github/settings.yml
>      permission: push
Yes, let’s leave it empty for now.

2023-04-10 14:59 UTC, SecurityCRob approved these changes

2023-04-10 20:27 UTC, balteravishay commented on .github/settings.yml
>      permission: push
fixed

2023-04-13 17:12 UTC, SecurityCRob approved these changes

2023-04-13 17:27 UTC, balteravishay commented on README.md
> +Safe languages like Rust, Go, and Java are less prone to these types of errors. The consequences of these vulnerabilities are not just technical, but can result in significant financial losses and in
fixed

2023-04-17 17:31 UTC, nellshamrell approved these changes

2023-04-27 16:28 UTC, merged